### ISSUE TITLE
Don't work after update

### ISSUE THREAD

**Issue by saruman9** [quosego/ghidra.hues#1]
Previous version (Ghidorah) works fine, but new (Hues) not. I build both version with gradle, then copy distribution archive to `Extensions/Ghidra` directory of Ghidra, then install via GUI. Ghidorah menu item became visible, but Hues don't.

**Comment by quosego** [comment]
Hey @saruman9, 
This should be resolved now. I was using a custom setting to load plugins instead of the default main/java the root path was switched. I reverted it back and rebuilt it. Checkout the recent releases.

**Comment by saruman9** [comment]
Thank you, @quosego! Distribution from releases works fine.

For building needed new dependency `com.intellij.uiDesigner` now?

It is possible to fix colours of rows in tables?

![2019-03-11_075313_762310820](https://user-images.githubusercontent.com/4244396/54101102-d0653e80-43d2-11e9-933e-252f2e5c255f.png)

**Comment by quosego** [comment]
No problem and glad to hear. 

Yeah, I was thinking about implementing intellij's theme into the selection and also wanted to draft a wireframe for the tool. Next release will switch back to native Java for the UI but may also provide context to switch themes differently since what I'm currently doing which is very hackish in regards to forcing all UI themes to switch over to the MetalTheme by default. 

I should offer more options to what ghidra supports:
https://github.com/quosego/ghidra.framework/blob/9a37abe80cac6f36d5655aa4e890b4a4644af61a/src/ghidra/docking/util/DockingWindowsLookAndFeelUtils.java

I been slowly picking away at additional windows and custom elements and will have a hacked out draft in the next release trying to address these.

**Comment by saruman9** [comment]
Thank you for detailed answer and explanation about options to what ghidra supports.
